-------------------------------------------------------------------------------
Test set: za.wethinkcode.Tests.AcceptanceTest.LaunchRobotTests
-------------------------------------------------------------------------------
Tests run: 3, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 0.003 s <<< FAILURE! - in za.wethinkcode.Tests.AcceptanceTest.LaunchRobotTests
launchBotInWorldWithObstacle  Time elapsed: 0.002 s  <<< ERROR!
java.lang.RuntimeException: Error connecting to Robot Worlds server.
	at za.wethinkcode.Tests.AcceptanceTest.LaunchRobotTests.connectToServer(LaunchRobotTests.java:30)
Caused by: java.net.ConnectException: Connection refused
	at za.wethinkcode.Tests.AcceptanceTest.LaunchRobotTests.connectToServer(LaunchRobotTests.java:30)

validLaunchShouldSucceed  Time elapsed: 0 s  <<< ERROR!
java.lang.RuntimeException: Error connecting to Robot Worlds server.
	at za.wethinkcode.Tests.AcceptanceTest.LaunchRobotTests.connectToServer(LaunchRobotTests.java:30)
Caused by: java.net.ConnectException: Connection refused
	at za.wethinkcode.Tests.AcceptanceTest.LaunchRobotTests.connectToServer(LaunchRobotTests.java:30)

invalidLaunchShouldFail  Time elapsed: 0 s  <<< ERROR!
java.lang.RuntimeException: Error connecting to Robot Worlds server.
	at za.wethinkcode.Tests.AcceptanceTest.LaunchRobotTests.connectToServer(LaunchRobotTests.java:30)
Caused by: java.net.ConnectException: Connection refused
	at za.wethinkcode.Tests.AcceptanceTest.LaunchRobotTests.connectToServer(LaunchRobotTests.java:30)

