-------------------------------------------------------------------------------
Test set: za.wethinkcode.Tests.AcceptanceTest.LaunchRobotTests
-------------------------------------------------------------------------------
Tests run: 5, Failures: 0, Errors: 5, Skipped: 0, Time elapsed: 0.508 s <<< FAILURE! - in za.wethinkcode.Tests.AcceptanceTest.LaunchRobotTests
launchBotWithSameName  Time elapsed: 0.081 s  <<< ERROR!
java.lang.RuntimeException: Error connecting to Robot Worlds server.
	at za.wethinkcode.Tests.AcceptanceTest.LaunchRobotTests.connectToServer(LaunchRobotTests.java:29)
Caused by: java.net.ConnectException: Connection refused
	at za.wethinkcode.Tests.AcceptanceTest.LaunchRobotTests.connectToServer(LaunchRobotTests.java:29)

launchAnotherBot  Time elapsed: 0.003 s  <<< ERROR!
java.lang.RuntimeException: Error connecting to Robot Worlds server.
	at za.wethinkcode.Tests.AcceptanceTest.LaunchRobotTests.connectToServer(LaunchRobotTests.java:29)
Caused by: java.net.ConnectException: Connection refused
	at za.wethinkcode.Tests.AcceptanceTest.LaunchRobotTests.connectToServer(LaunchRobotTests.java:29)

launchBotInWorldWithObstacle  Time elapsed: 0.002 s  <<< ERROR!
java.lang.RuntimeException: Error connecting to Robot Worlds server.
	at za.wethinkcode.Tests.AcceptanceTest.LaunchRobotTests.connectToServer(LaunchRobotTests.java:29)
Caused by: java.net.ConnectException: Connection refused
	at za.wethinkcode.Tests.AcceptanceTest.LaunchRobotTests.connectToServer(LaunchRobotTests.java:29)

validLaunchShouldSucceed  Time elapsed: 0.003 s  <<< ERROR!
java.lang.RuntimeException: Error connecting to Robot Worlds server.
	at za.wethinkcode.Tests.AcceptanceTest.LaunchRobotTests.connectToServer(LaunchRobotTests.java:29)
Caused by: java.net.ConnectException: Connection refused
	at za.wethinkcode.Tests.AcceptanceTest.LaunchRobotTests.connectToServer(LaunchRobotTests.java:29)

invalidLaunchShouldFail  Time elapsed: 0.002 s  <<< ERROR!
java.lang.RuntimeException: Error connecting to Robot Worlds server.
	at za.wethinkcode.Tests.AcceptanceTest.LaunchRobotTests.connectToServer(LaunchRobotTests.java:29)
Caused by: java.net.ConnectException: Connection refused
	at za.wethinkcode.Tests.AcceptanceTest.LaunchRobotTests.connectToServer(LaunchRobotTests.java:29)

